class StepikUserAlreadyRegisteredException(Exception): ...


class StepikInvalidPasswordException(Exception): ...


class StepikLoginException(Exception): ...


class StepikRegistrationException(Exception): ...


class StepikEnrollmentException(Exception): ...
